<a href="https://colab.research.google.com/github/LuhemRevorg/Deep-Learning/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Imports**

In [2]:
import torch
import numpy as np

A torch.Tensor is a multi dimensional matrix containing elements of a single data type. Works better with GPU, dfeault data type is float32

In [ ]:
# Lists

my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [ ]:
# Numpy Arrays

np1 = np.random.rand(3,4)
np1

array([[0.01444739, 0.34550789, 0.3183109 , 0.46050743],
       [0.92685468, 0.46849723, 0.28041068, 0.21760798],
       [0.70920167, 0.17424025, 0.80043808, 0.037459  ]])

In [ ]:
# Tensor


tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8043, -0.3902,  0.1289,  0.1111],
        [ 0.0146,  0.7709,  0.5713, -0.5537],
        [-0.4271,  1.2827, -0.6697,  0.8531]])

In [ ]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0144, 0.3455, 0.3183, 0.4605],
        [0.9269, 0.4685, 0.2804, 0.2176],
        [0.7092, 0.1742, 0.8004, 0.0375]], dtype=torch.float64)

# **Tensor Ops**

In [ ]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch = my_torch.reshape(2,-1) # Use -1 when don't know number of elements
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
my_torch2 = my_torch.view(5,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
# Reshape and view update the tensor

my_torch3 = torch.arange(10)
my_torch3

my_torch4 = my_torch3.reshape(2,5)
my_torch4

my_torch3[1] = 1000
my_torch3
my_torch4



tensor([[   0, 1000,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
# Slices

my_torch5 = torch.arange(10)
my_torch5[7]
my_torch5 = my_torch5.reshape(5,2)
my_torch5


my_torch5[:,1]
my_torch5[:,1:]


tensor([[1],
        [3],
        [5],
        [7],
        [9]])

## **Mathematical Operations on Tensors**

In [4]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])



In [8]:
# Addition Shorthand
print(tensor_a + tensor_b)
# Addition Longhand
print(torch.add(tensor_a,tensor_b))

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


In [11]:
# Subtraction Shorthand
print(tensor_a - tensor_b)
# Subtraction Longhand
print(torch.sub(tensor_a,tensor_b))

tensor([-4, -4, -4, -4])
tensor([-4, -4, -4, -4])


In [12]:
# Multiplication Shorthand
print(tensor_a * tensor_b)
# Multiplication Longhand
print(torch.mul(tensor_a,tensor_b))

tensor([ 5, 12, 21, 32])
tensor([ 5, 12, 21, 32])


In [13]:
# Division Shorthand
print(tensor_a / tensor_b)
# Division Longhand
print(torch.div(tensor_a,tensor_b))

tensor([0.2000, 0.3333, 0.4286, 0.5000])
tensor([0.2000, 0.3333, 0.4286, 0.5000])


In [14]:
# Remainder Modulus Shorthand
print(tensor_b % tensor_a)
# Remainder Modulus Longhand
print(torch.remainder(tensor_b,tensor_a))

tensor([0, 0, 1, 0])
tensor([0, 0, 1, 0])


In [15]:
# Exponent / Power Shorthand
print(tensor_a ** tensor_b)
# Exponent / Power Longhand
print(torch.pow(tensor_a,tensor_b))

tensor([    1,    64,  2187, 65536])
tensor([    1,    64,  2187, 65536])


In [16]:
# Reassignment

#tensor_a += tensor_b

tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])